"""change to longtext

Revision ID: 196ec3e5d849
Revises: 21b99b5e3a06
Create Date: 2025-08-04 22:53:45.718315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196ec3e5d849'
down_revision = '21b99b5e3a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('training_item_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_list', ['training_list_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('training_item_ibfk_1'), 'training_list', ['training_list_id'], ['id'])

    # ### end Alembic commands ###
