"""Recreate training_lang table

Revision ID: 21b99b5e3a06
Revises: f24a957ae00f
Create Date: 2025-07-27 21:14:57.817433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b99b5e3a06'
down_revision = 'f24a957ae00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_list', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'training_lang', ['lang_from'], ['lang_code'])
        batch_op.create_foreign_key(None, 'training_lang', ['lang_to'], ['lang_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
