"""Add TextForReading, TrainingList, and TrainingItem models

Revision ID: 2dc39eb70eba
Revises: 65ec517cbb62
Create Date: 2025-07-24 16:50:29.119118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc39eb70eba'
down_revision = '65ec517cbb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_for_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['text_for_reading.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=200), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('num_first_attempt', sa.Integer(), nullable=True),
    sa.Column('num_second_attempt', sa.Integer(), nullable=True),
    sa.Column('num_extra_attempt', sa.Integer(), nullable=True),
    sa.Column('num_skipped', sa.Integer(), nullable=True),
    sa.Column('last_trained_at', sa.DateTime(), nullable=True),
    sa.Column('last_result', sa.String(length=50), nullable=True),
    sa.Column('training_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['training_list_id'], ['training_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_item')
    op.drop_table('training_list')
    op.drop_table('text_for_reading')
    # ### end Alembic commands ###
