"""Add training_order to TrainingItem

Revision ID: 543c52bc25e5
Revises: 2dc39eb70eba
Create Date: 2025-07-24 19:45:54.993901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543c52bc25e5'
down_revision = '2dc39eb70eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_item', schema=None) as batch_op:
        batch_op.drop_column('training_order')

    # ### end Alembic commands ###
