"""change to longtext

Revision ID: 616871de37e8
Revises: 196ec3e5d849
Create Date: 2025-08-05 10:33:16.682458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '616871de37e8'
down_revision = '196ec3e5d849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_for_reading', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_for_reading', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
