"""column url2 added

Revision ID: 88e65b3c2ce2
Revises: 616871de37e8
Create Date: 2025-08-05 10:55:54.754332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88e65b3c2ce2'
down_revision = '616871de37e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_for_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url2', sa.String(length=500), nullable=True))
        batch_op.alter_column('content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_for_reading', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.drop_column('url2')

    # ### end Alembic commands ###
