"""Add lang_from and lang_to to TrainingList

Revision ID: f24a957ae00f
Revises: 543c52bc25e5
Create Date: 2025-07-27 19:10:41.755858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f24a957ae00f'
down_revision = '543c52bc25e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_lang')
    with op.batch_alter_table('training_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang_from', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('lang_to', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_list', schema=None) as batch_op:
        batch_op.drop_column('lang_to')
        batch_op.drop_column('lang_from')

    op.create_table('training_lang',
    sa.Column('lang_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('lang_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('native_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('lang_code'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
